require 'bcrypt'
require 'digest'
require 'json'
require 'pry'
require 'sinatra/base'
require 'sqlite3'
require 'securerandom'

require_relative 'lord_of_war/version'
require_relative 'lord_of_war/monkeypatch'
require_relative 'lord_of_war/utils'
require_relative 'lord_of_war/filters'
require_relative 'lord_of_war/pagination'
require_relative 'lord_of_war/product'
require_relative 'lord_of_war/user'
require_relative 'lord_of_war/account'
require_relative 'lord_of_war/store'
require_relative 'lord_of_war/api'
